version: 2

models:
  - name: new_users
    description: View of users created in the last 24 hours.
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: created_at
        tests:
          - not_null
  - name: stg_users
    description: Users table.
    columns:
      - name: id
        tests:
          - unique
          - not_null